"""added rewards table

Revision ID: f2c7d5ca2fa3
Revises: 
Create Date: 2024-09-26 10:40:27.137068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c7d5ca2fa3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_reward', schema=None) as batch_op:
        batch_op.drop_constraint('order_id', type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('date_earned')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('reward_amount')

    with op.batch_alter_table('customer_reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_earned', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###
